version: '3.4'

services:
  gem.powerplant.api:
    image: ${DOCKER_REGISTRY-}gempowerplantapi
    ports: 
      - "8888:80"
    build:
      context: .
      dockerfile: source/GEM.PowerPlant.Api/Dockerfile
  seq:
    image: datalust/seq:latest