version: '3.4'

services:
  gem.powerplant.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"